### ISSUE TITLE
 ydbdash.sh script

### ISSUE THREAD

**Issue by wwongpai** [RamSailopal/YottaDB-dashboard#2]
Hi Raman,

Thank you for this wonderful extension.  
Anyway I have been trying to scrape a metric from port 8001, but nothing shown up in Prometheus server side. I run "./ydbdash.sh start" with port 8001, I can't see 8001 as LISTEN port. I'm not sure if I miss somethings. If possible, pls kindly advise on this.

Thanks!

**Comment by RamSailopal** [comment]
Hi,

Try running the python script directly. First run:

export YOTTA_PROM_PORT="8001"

and then:

./ydbdash.py

This will run the process to the foreground

Also make sure that the top line of the script references an actual executable i.e. if /usr/bin/python doesn't exist on your system, change the line to the path of your installed Python.

**Comment by wwongpai** [comment]
Thanks a lot!

I have been trying following your advise, found this error..
`host:~/YottaDB-dashboard$ ./ydbdash.py 
Traceback (most recent call last):
  File "./ydbdash.py", line 442, in <module>
    REGISTRY.register(CustomCollector())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "./ydbdash.py", line 285, in collect
    a.add_metric([title], int(stats[0]))
ValueError: invalid literal for int() with base 10: ''`

I am trying to run from python3 and python2. got the same error. Is this about passing float() into int()?

**Comment by RamSailopal** [comment]
Do you have YottaDB installed on the system and a link to the ydb executable in the system path?

**Comment by wwongpai** [comment]
Hi Raman,

Yes, there's YottaDb installed and link to the ydb executable properly

host:~/.yottadb$ tree
.
├── V6.3-010_x86_64 -> r1.32_x86_64
├── r
│   ├── TESTROUT.m
│   ├── _zmgsilog.m
│   ├── gvstat.m
│   ├── gvstatprom.m

├── r1.32_x86_64
│   ├── g
│   │   ├── %ydbaim.dat
│   │   ├── %ydbocto.dat
│   │   ├── %ydbocto.mjl
│   │   ├── yottadb.dat
│   │   ├── yottadb.gld
│   │   └── yottadb.mjl
│   ├── o
│   │   ├── TESTROUT.o
│   │   ├── gvstat.o
│   │   ├── gvstatprom.o
│   │   └── utf8
│   └── r

Anyway do I miss anything? 
Thanks and really appreciate your response.

**Comment by RamSailopal** [comment]
Do you have any routines at  /data/yottadb/r1.32_x86_64/r level?

Also try to manually enter the yottadb environment from the command line through entering:

ydb

Then enter:

D proc^gvstatprom("DEFAULT")

and:

D accproc^gvstatprom("DEFAULT")

See if you get any errors.

**Comment by RamSailopal** [comment]
Looking at the line numbers associated with the error, it may actually be the following command that is the issue:

ydb <<< "D ^%FREECNT" | awk -v reg="DEFAULT" '$0 ~ reg { gsub("[%)]","",$5);printf "%s,%s,%s",$2,$3,$5 }'

Try and run it manually from the command line

**Comment by wwongpai** [comment]
Hi Raman,

I can run above commands without any error. However once run ydbdash.py, still got the same error as earlier.

I have routines at yottadb/r1.32_x86_64/r level as below, 

ubuntu@host:~/.yottadb$ tree
.
├── V6.3-010_x86_64 -> r1.32_x86_64
├── r
│   ├── TESTROUT.m
│   ├── _zmgsilog.m
│   ├── gvstat.m
│   ├── gvstatprom.m
├── r1.32_x86_64
│   ├── g
│   │   ├── %ydbaim.dat
│   │   ├── %ydbocto.dat
│   │   ├── %ydbocto.mjl
│   │   ├── yottadb.dat
│   │   ├── yottadb.gld
│   │   └── yottadb.mjl
│   ├── o
│   │   ├── TESTROUT.o
│   │   ├── gvstat.o
│   │   ├── gvstatprom.o
│   │   └── utf8
│   └── r
│       ├── _zmgsilog.m
│       ├── gvstat.m
│       └── gvstatprom.m

If we run ydbdash.sh instead, how to fix it to run as a foreground to be exposed metric for scraping?
Thanks.

**Comment by RamSailopal** [comment]
What versions of Python 2 and 3 are you using?

**Comment by wwongpai** [comment]
Hi Raman,

I am running Python3. Is there any required version for python?

Additionally, I run the following code in python3 console. There's an error when execute the following, 
cmd = "ydb <<< "D ^%FREECNT" | awk -v reg="" + reg + "" '$0 ~ reg { gsub("[%)]","",$5);printf "%s,%s,%s",$2,$3,$5 }'"
as following,

```
>>> cmd = "ydb <<< "D ^%FREECNT" | awk -v reg="" + reg + "" '$0 ~ reg { gsub("[%)]","",$5);printf "%s,%s,%s",$2,$3,$5 }'"
  File "<stdin>", line 1
    cmd = "ydb <<< "D ^%FREECNT" | awk -v reg="" + reg + "" '$0 ~ reg { gsub("[%)]","",$5);printf "%s,%s,%s",$2,$3,$5 }'"
                    ^
SyntaxError: invalid syntax
```
Then tried to run the following instead, and still an error
```
>>> import os
>>> reg=os.environ.get('YOTTA_PROM_REG')
>>> cmd = "ydb <<< \"D ^%FREECNT\" | awk -v reg=\"" + reg + "\" '$0 ~ reg { gsub(\"[%)]\",\"\",$5);printf \"%s,%s,%s\",$2,$3,$5 }'"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only concatenate str (not "NoneType") to str

```
Can't run further as next step requires cmd variable.

Is there any something I missed and need to change. 
Thank you.

**Comment by RamSailopal** [comment]
Since you are getting a syntax error with awk, can I ask you to post your version of awk? Type:

awk -V

at the command prompt. A lot of the awk code uses functions specifics to the GNU version of awk

**Comment by wwongpai** [comment]
Hi Raman,

After input reg = '8001', then code can be run successfully. However the final result is still NULL as stats value got blank.

I have checked and found there's something wrong since running result = process.communicate()
```
>>> print(process)
<subprocess.Popen object at 0x7f0ab32eb100>
>>> result = process.communicate()
>>> print(result)
(b'', b'/bin/sh: 1: Syntax error: redirection unexpected\n')
```
I re-check whether there's output from %FREECNT and it works properly.

```
YDB>D ^%FREECNT
Region          Free     Total          Database file
------          ----     -----          -------------
DEFAULT         4998      5000 (100.0%) /home/ubuntu/.yottadb/r1.32_x86_64/g/yottadb.dat
YDBAIM         19998     20000 (100.0%) /home/ubuntu/.yottadb/r1.32_x86_64/g/%ydbaim.dat
YDBOCTO         9998     10000 (100.0%) /home/ubuntu/.yottadb/r1.32_x86_64/g/%ydbocto.dat
```

What's the expected outcome from process.communicate()?
Thanks.

**Comment by RamSailopal** [comment]
The value of the variable reg is determined by the environmental variable YOTTA_PROM_REG. If this is not set, reg will default to "DEFAULT"

**Comment by RamSailopal** [comment]
Are you running bash or sh from the command line when it runs successfully?

**Comment by wwongpai** [comment]
Hi Raman,

I am running from Python console,

```
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 

>>> import subprocess
>>> from prometheus_client.core import GaugeMetricFamily, StateSetMetricFamily, REGISTRY, CounterMetricFamily
>>> from prometheus_client import start_http_server, Enum
>>> reg='DEFAULT'
>>> cmd = "ydb <<< \"D ^%FREECNT\" | awk -v reg=\"" + reg + "\" '$0 ~ reg { gsub(\"[%)]\",\"\",$5);printf \"%s,%s,%s\",$2,$3,$5 }'"
>>> process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True) 
>>> print(process)
<subprocess.Popen object at 0x7fd6e624f460>
>>> result = process.communicate()
>>> print(result)
(b'', b'/bin/sh: 1: Syntax error: redirection unexpected\n')
```

run from python script got the same error,

**Comment by RamSailopal** [comment]
OK from the feedback so far, the command line:

ubuntu@host:~/.yottadb/r1.32_x86_64/r$ ydb <<< "D ^%FREECNT" | awk -v reg="DEFAULT" '$0 ~ reg { gsub("[%)]","",$5);printf "%s,%s,%s",$2,$3,$5 }'
4987,5000,99.7

Returns the data required. Namely the Amount of Free space in the ydb DEFAULT region, the total space in the ydb DEFAULT region and the % free space in the ydb DEFAULT region.

When the command is actioned from Python, the command is failing though.

Try print(cmd) in Python to ensure that the cmd generated from within Python matches the one actioned from the command line (the command that works).

**Comment by RamSailopal** [comment]
Strictly the awk command should have brackets around printf and so should be:

ydb <<< "D ^%FREECNT" | awk -v reg="DEFAULT" '$0 ~ reg { gsub("[%)]","",$5);printf("%s,%s,%s",$2,$3,$5) }'

Therefore try:

>>> import subprocess
>>> from prometheus_client.core import GaugeMetricFamily, StateSetMetricFamily, REGISTRY, CounterMetricFamily
>>> from prometheus_client import start_http_server, Enum
>>> reg='DEFAULT'
>>> cmd = "ydb <<< \"D ^%FREECNT\" | awk -v reg=\"" + reg + "\" '$0 ~ reg { gsub(\"[%)]\",\"\",$5);printf( \"%s,%s,%s\",$2,$3,$5) }'"
>>> process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True) 
>>> result = process.communicate()
>>> print(result)

**Comment by wwongpai** [comment]
Got the same result,

Python 3.8.10 (default, Jun  2 2021, 10:49:15) 

```
>>> import subprocess
>>> from prometheus_client.core import GaugeMetricFamily, StateSetMetricFamily, REGISTRY, CounterMetricFamily
>>> from prometheus_client import start_http_server, Enum
>>> reg='DEFAULT'
>>> cmd = "ydb <<< "D ^%FREECNT" | awk -v reg="" + reg + "" '$0 ~ reg { gsub("[%)]","",$5);printf( "%s,%s,%s",$2,$3,$5) }'"
  File "<stdin>", line 1
    cmd = "ydb <<< "D ^%FREECNT" | awk -v reg="" + reg + "" '$0 ~ reg { gsub("[%)]","",$5);printf( "%s,%s,%s",$2,$3,$5) }'"
                    ^
SyntaxError: invalid syntax
```

Then change to run this instead,

```
>>> cmd = "ydb <<< \"D ^%FREECNT\" | awk -v reg=\"" + reg + "\" '$0 ~ reg { gsub(\"[%)]\",\"\",$5);printf(\"%s,%s,%s\",$2,$3,$5) }'"
>>> print(cmd)
ydb <<< "D ^%FREECNT" | awk -v reg="DEFAULT" '$0 ~ reg { gsub("[%)]","",$5);printf("%s,%s,%s",$2,$3,$5) }'
>>> process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
>>> print(process)
<subprocess.Popen object at 0x7feb69244460>
>>> result = process.communicate()
>>> print(result)
(b'', b'/bin/sh: 1: Syntax error: redirection unexpected\n')
```
Is it correct that the process return "<subprocess.Popen object at 0x7feb69244460>"?

Thanks,
Warach

**Comment by RamSailopal** [comment]
OK, I get the feeling that your default shell isn't bash and so we may need to change the cmd variable to explicitly specify bash. Try:

>>> import subprocess
>>> from prometheus_client.core import GaugeMetricFamily, StateSetMetricFamily, REGISTRY, CounterMetricFamily
>>> from prometheus_client import start_http_server, Enum
>>> reg='DEFAULT'
>>>cmd = "/bin/bash -c \"ydb <<< \\\"D ^%FREECNT\\\" | awk -v reg=\\\"" + reg + "\\\" '\\$0 ~ reg { gsub(\\\"[%)]\\\",\\\"\\\",\\$5);printf(\\\"%s,%s,%s\\\",\\$2,\\$3,\\$5)}'\""
>>> process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
>>> print(process)
<subprocess.Popen object at 0x7feb69244460>
>>> result = process.communicate()
>>> print(result)

**Comment by RamSailopal** [comment]
Did you manage to get any further with this?

**Comment by wwongpai** [comment]
Hi Raman,

Sorry for late response.
I managed to run on Python console successfully. It was all about shell that causing the error before, even my default shell is bash. Once change the cmd variable to explicitly specify bash, then all codes can be run successfully in the Python console.

I have been trying to change in the ydbdash.py code accordingly to explicitly specify bash in every lines that is required bash to run ydb command. It's still not 100% completed. Anyway let close this issue.

Thanks for asking, really appreciate.
Warach

**Comment by RamSailopal** [comment]
No worries Warach, I'll close the issue.
